### ISSUE TITLE
[LEGACY] ⭐️ Icon Requests

### ISSUE THREAD

**Issue by brionmario** [wso2/oxygen-ui#272]
This umbrella issue will keep track of the Icon Requests.

> [!NOTE]
> Create a separate issue (see [ref](https://github.com/wso2/oxygen-ui/issues/244)) and a maintainer will track it here. 
> ⚠️ Please do not add requests in this issue as comments. 

### Internal

- [x] BanIcon - Requested by @brionmario - https://github.com/wso2/oxygen-ui/pull/273
- [x] BuildingAltIcon - Requested by @brionmario - https://github.com/wso2/oxygen-ui/pull/273
- [x] EllipsisIcon - Requested by @brionmario - https://github.com/wso2/oxygen-ui/pull/273
- [x] EllipsisVerticalIcon - Requested by @brionmario  - https://github.com/wso2/oxygen-ui/pull/273
- [x] PenToSquareIcon - Requested by @brionmario - https://github.com/wso2/oxygen-ui/pull/273
- [x]  CircleInfoFilled - Requested by @brionmario - https://github.com/wso2/oxygen-ui/pull/309
- [x]  ChevronsLeft - Requested by @brionmario - https://github.com/wso2/oxygen-ui/pull/309
- [x]  ChevronsRight - Requested by @brionmario - https://github.com/wso2/oxygen-ui/pull/309
- [x]  GridDotsVertical - Requested by @adibmbrk - https://github.com/wso2/oxygen-ui/pull/312
### External

TODO
