### ISSUE TITLE
[Deprecations] Tracker for the deprecations that has to be removed in v2.0.0

### ISSUE THREAD

**Issue by brionmario** [wso2/oxygen-ui#285]
☂️ Umbrella issue to track the deprecations done in `1.x` version that has to be removed in `v2.0.0` or later

1. `CountryFlagsProps`

This is a typo and the correct spelling should be `CountryFlagProps`.

**Deprecated in**:
    - **Version**: v1.14.0
    - **PR**: https://github.com/wso2/oxygen-ui/pull/281
    - **Author**: @brionmario
**To be removed in**
    - **Version**: v2.0.0
**Checklist**
    - [ ] Deprecation notice added as a TSDoc comment
    - [ ] Marked as deprecated in the upcoming release preparation umbrella issu

**Comment by brionmario** [comment]
#### `CountryFlagsProps`

This is a typo and the correct spelling should be `CountryFlagProps`.

**Deprecated in**:
- **Version**: v1.14.0
- **PR**: https://github.com/wso2/oxygen-ui/pull/281
- **Author**: @brionmario
  
**To be removed in**
- **Version**: v2.0.0

**Checklist**
- [ ] Deprecation notice added as a TSDoc comment
- [ ] Marked as deprecated in the upcoming release preparation umbrella issue

**Comment by brionmario** [comment]
### enums in prop types

We should not use `enums` in prop types as highlighted in https://github.com/wso2/oxygen-ui/issues/286.

**Deprecated in**:
- **Version**: v1.14.0
- **PR**: https://github.com/wso2/oxygen-ui/pull/282
- **Author**: @brionmario
  
**To be removed in**
- **Version**: v2.0.0

**Checklist**
- [ ] Deprecation notice added as a TSDoc comment
- [ ] Marked as deprecated in the upcoming release preparation umbrella issue

**Comment by brionmario** [comment]
### `Tabs` component

Should directly use `Tab` from `@oxygen-ui/react/Tab` instead of this wrapper.

**Deprecated in**:
- **Version**: v2.3.5
- **PR**: https://github.com/wso2/oxygen-ui/pull/287
- **Author**: @brionmario
  
**To be removed in**
- **Version**: v3.0.0

**Checklist**
- [x] Deprecation notice added as a TSDoc comment
- [x] Mark as breaking change in the upcoming release preparation [umbrella issue](https://github.com/wso2/oxygen-ui/issues/284)
